# Generated by Django 6.0.3 on 2026-03-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_venta',
            field=models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
